# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64175c932e6da968b327f8a21f8bb338b864b0c650de1c6144fbce4b1b10398149a66669db5971b3d33a3385cd22738c496abc699744b23d405e61ef88b9c275

test:
  secret_key_base: 72295e0efd81e1eee8d299112100b9b65b625e45e503e501ce2a86d5778cc885cf2bc6d6516c5f4630cf5edebba766c92961f211649a1a1ca4c7ad28efc28a21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
